
:- assert_clauses(n(gcd,3),[
 clause([n(gcd,3),$(x),$(y),$(d)],
  [\/,[&,[n(@=<,2),$(x),$(y)],[n(gcd_leq,3),$(x),$(y),$(d)]],[&,[~,[n(@=<,2),$(x),$(y)]],[n(gcd_leq,3),$(y),$(x),$(d)]]],
  [x,y,d]/0)
]).

:- assert_clauses(n(gcd_leq,3),[
 clause([n(gcd_leq,3),$(x),$(y),$(d)],
  [\/,[&,[=,$(x),[n(0,0)]],[=,$(d),$(y)]],[&,[~,[=,$(x),[n(0,0)]]],[n(plus,3),$(x),$(z),$(y)],[n(gcd,3),$(x),$(z),$(d)]]],
  [x,y,d,z]/0)
]).
