%:- compile_gr($(examples)/parser/src/grammar).
%:- compile_gr($(examples)/parser/src/read).
%:- compile_gr($(examples)/parser/src/write).
:- ['axioms.pr'].
:- ['precedence.pr'].
:- ['grammar.pr'].
:- ['soundness.pr'].
:- ['completeness.pr'].
:- ['uniqueness.pr'].
:- ['termination.pr'].
:- ['write.pr'].
:- ['parser.pr'].
