
:- assert_clauses(n(a,0),[
 clause([n(a,0)],
  [&],
  []/0),
 clause([n(a,0)],
  [&,[n(b1,0)],[n(b2,0)],[n(b3,0)]],
  []/0),
 clause([n(a,0)],
  [n(c1,0)],
  []/0),
 clause([n(a,0)],
  [&,[n(d1,0)],[n(d2,0)]],
  []/0)
]).

:- assert_clauses(n(append,3),[
 clause([n(append,3),[n([],0)],$(l),$(l)],
  [&],
  [l]/0),
 clause([n(append,3),[n('.',2),$(x),$(l1)],$(l2),[n('.',2),$(x),$(l3)]],
  [n(append,3),$(l1),$(l2),$(l3)],
  [x,l1,l2,l3]/0)
]).

:- assert_clauses(n(list,1),[
 clause([n(list,1),[n([],0)]],
  [&],
  []/0),
 clause([n(list,1),[n('.',2),$(0),$(l)]],
  [n(list,1),$(l)],
  [0,l]/1)
]).

:- assert_clauses(n(member,2),[
 clause([n(member,2),$(x),[n('.',2),$(x),$(0)]],
  [&],
  [x,0]/1),
 clause([n(member,2),$(x),[n('.',2),$(0),$(l)]],
  [n(member,2),$(x),$(l)],
  [x,0,l]/1)
]).

:- assert_clauses(n(notsubset,2),[
 clause([n(notsubset,2),$(l1),$(l2)],
  [&,[n(member,2),$(x),$(l1)],[~,[n(member,2),$(x),$(l2)]]],
  [l1,l2,x]/0)
]).

:- assert_clauses(n(subset,2),[
 clause([n(subset,2),$(l1),$(l2)],
  [~,[n(notsubset,2),$(l1),$(l2)]],
  [l1,l2]/0)
]).
